server:
  port: 8085

spring:
  application:
    name: apigateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/biblioteca
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: circulacion-service
          uri: http://localhost:8083
          predicates:
            - Path=/circulacion/**
        - id: catalogo-service
          uri: http://localhost:8082
          predicates:
            - Path=/catalogo/**
        - id: usuario-service
          uri: http://localhost:8081
          predicates:
            - Path=/usuarios/**
        - id: notificacion-service
          uri: http://localhost:8084
          predicates:
            - Path=/notificaciones/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG